# Scilint Pre-commit Hooks
# Install: Add to your .pre-commit-config.yaml:
#
#   repos:
#     - repo: https://github.com/scilint/scilint
#       rev: v1.0.0
#       hooks:
#         - id: scilint
#

- id: scilint
  name: Scilint (Scientific Integrity)
  description: Detects computational mirages, data leakage, and scientific integrity issues.
  entry: scilint analyze
  language: python
  types: [python]
  args: ['--format', 'text']

- id: scilint-mirage
  name: Scilint Mirage Detection
  description: Detects computational mirages (variance-destroying operations).
  entry: scilint mirage
  language: python
  types: [python]

- id: scilint-leakage
  name: Scilint Leakage Detection
  description: Detects train/test data leakage.
  entry: scilint leakage
  language: python
  types: [python]

- id: scilint-hypothesis
  name: Scilint Hypothesis Guard
  description: Detects p-hacking and statistical validity issues.
  entry: scilint hypothesis
  language: python
  types: [python]

- id: scilint-units
  name: Scilint Unit Guard
  description: Checks dimensional consistency and unit mismatches.
  entry: scilint units
  language: python
  types: [python]

- id: scilint-tensor
  name: Scilint Tensor Guard
  description: Checks deep learning integrity (gradient death, normalization blindness).
  entry: scilint tensor
  language: python
  types: [python]
