# Demyst Pre-commit Hooks
# Install: Add to your .pre-commit-config.yaml:
#
#   repos:
#     - repo: https://github.com/demyst/demyst
#       rev: v1.0.0
#       hooks:
#         - id: demyst
#

- id: demyst
  name: Demyst (Scientific Integrity)
  description: Detects computational mirages, data leakage, and scientific integrity issues.
  entry: demyst analyze
  language: python
  types: [python]
  args: ['--format', 'text']

- id: demyst-mirage
  name: Demyst Mirage Detection
  description: Detects computational mirages (variance-destroying operations).
  entry: demyst mirage
  language: python
  types: [python]

- id: demyst-leakage
  name: Demyst Leakage Detection
  description: Detects train/test data leakage.
  entry: demyst leakage
  language: python
  types: [python]

- id: demyst-hypothesis
  name: Demyst Hypothesis Guard
  description: Detects p-hacking and statistical validity issues.
  entry: demyst hypothesis
  language: python
  types: [python]

- id: demyst-units
  name: Demyst Unit Guard
  description: Checks dimensional consistency and unit mismatches.
  entry: demyst units
  language: python
  types: [python]

- id: demyst-tensor
  name: Demyst Tensor Guard
  description: Checks deep learning integrity (gradient death, normalization blindness).
  entry: demyst tensor
  language: python
  types: [python]
